# Generated by Django 5.1.6 on 2025-03-19 19:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_coursespage_banner_image'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('introduction', wagtail.fields.RichTextField(blank=True)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, max_length=255)),
                ('event_date', models.DateField()),
                ('event_overview', wagtail.fields.RichTextField(blank=True)),
                ('sections', wagtail.fields.StreamField([('add_on', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('image_or_video', 0), ('title', 1), ('text', 2)]], {})}, help_text='Add as many sections as you want')),
                ('testimonial1', wagtail.fields.RichTextField(blank=True)),
                ('testimonial1_author', models.CharField(blank=True, max_length=255)),
                ('testimonial2', wagtail.fields.RichTextField(blank=True)),
                ('testimonial2_author', models.CharField(blank=True, max_length=255)),
                ('testimonial3', wagtail.fields.RichTextField(blank=True)),
                ('testimonial3_author', models.CharField(blank=True, max_length=255)),
                ('cta_title', models.CharField(blank=True, max_length=255)),
                ('cta_text', wagtail.fields.RichTextField(blank=True)),
                ('cta_button_text', models.CharField(blank=True, max_length=50)),
                ('cta_button_link', models.URLField(blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
