# Generated by Django 5.1.6 on 2025-03-19 20:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blogpage_eventpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='cta_button_link',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='cta_button_text',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='cta_title',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='testimonial1',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='testimonial1_author',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='testimonial2',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='testimonial2_author',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='testimonial3',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='testimonial3_author',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonials', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('user', 0), ('quote', 1)]], {})}, help_text='Add as many testimonials as you want'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='sections',
            field=wagtail.fields.StreamField([('sections', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('image_or_video', 0), ('title', 1), ('text', 2)]], {})}, help_text='Add as many sections as you want'),
        ),
    ]
