# Generated by Django 5.1.7 on 2025-03-20 08:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_eventpage_cta_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='sections',
            field=wagtail.fields.StreamField([('sections', 3)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'required': True}), 3: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2)]], {})}, help_text='Add as many sections as you want'),
        ),
    ]
